### ISSUE TITLE
Login issues with Hive

### ISSUE THREAD

**Issue by TheNetWhiz** [ledgerconnect/hivesigner#22] opened 2020-09-06 18:29 UTC
### Expected behavior
Be able to use Hive one time to login to my Hive account for DLease and others.

### Actual behavior
It goes to a spinning logo and never completes.

### Steps to reproduce the behavior
Use my username and key and it goes no where. This has been happening for months. It even happened with SteemConnect but that got fixed.

**Comment by feruzm** [comment] 2020-09-06 18:35
@TheNetWhiz What key did you try? Can you check dev console and see if you get any errors messages there?
When was it fixed in steemconnect?

**Comment by TheNetWhiz** [comment] 2020-09-06 18:54
Sorry, meant my HiveSigner password. Can’t say for sure when it was fixed. I think late July or early August.

- Drew Dupont

**Comment by feruzm** [comment] 2020-09-06 18:57
Right now, every account you import can have different Hivesigner passwords, could it be that you are trying different/wrong Hivesigner password for that particular account? You can always delete and re-add account and see if it helps? https://hivesigner.com/accounts

**Comment by TheNetWhiz** [comment] 2020-09-06 19:06
I tried again. I deleted the account and reimported it. I then tried to create the HiveSigner password, but it sits there spinning and goes no where. The password is only 24 characters with letters, numbers, and special characters.

- Drew Dupont

**Comment by feruzm** [comment] 2020-09-06 19:09
If you are using chrome, could you please check if you have any errors in console when you get non-stop spinning. This is how you check dev console in Chrome. In that error, I would be able to see what is causing it.

`To open the developer console in Google Chrome, open the Chrome Menu in the upper-right-hand corner of the browser window and select More Tools > Developer Tools. You can also use the shortcut Option + ⌘ + J (on macOS), or Shift + CTRL + J (on Windows/Linux).`

**Comment by TheNetWhiz** [comment] 2020-09-06 20:16
I am using Safari on an iPad. Chrome on iOS does not have a dev option. I have not tried on a desktop.

- Drew Dupont

**Comment by feruzm** [comment] 2020-09-07 14:28
I couldn't reproduce this issue, could you remove account and import account again only this time, uncheck `Encrypt your keys` box?

**Comment by TheNetWhiz** [comment] 2020-09-07 15:46
Removed account. Imported with name and private key. Encrypt keys is unchecked. Nothing changed.
   
  
    
   
  
   Now tried in Chrome on Windows and got this in the error console:
   
  
   [code]contentScript.js:3092 [Sep 7, 11:42:49 am] [contentScript]: [INFO]: Initialising TronLink
   contentScript.js:3092 [Sep 7, 11:42:49 am] [contentScript]: [INFO]: TronLink injected
   pageHook.js:42704 [Sep 7, 11:42:49 am] [ProxiedProvider]: [INFO]: Provider initialised
   2pageHook.js:42704 [Sep 7, 11:42:50 am] [ProxiedProvider]: [INFO]: Provider initialised
   pageHook.js:42704 [Sep 7, 11:42:50 am] [ProxiedProvider]: [INFO]: Request to wallet/getnodeinfo has been queued
   3pageHook.js:42704 [Sep 7, 11:42:50 am] [ProxiedProvider]: [INFO]: Provider initialised
   pageHook.js:42704 [Sep 7, 11:42:50 am] [ProxiedProvider]: [INFO]: Request to wallet/getnodeinfo has been queued
   3pageHook.js:42704 [Sep 7, 11:42:50 am] [ProxiedProvider]: [INFO]: Provider initialised
   pageHook.js:42704 [Sep 7, 11:42:50 am] [ProxiedProvider]: [INFO]: Request to wallet/getnodeinfo has been queued
   pageHook.js:42704 [Sep 7, 11:42:50 am] [pageHook]: [INFO]: TronLink initiated
   inpage.js:1 MetaMask: MetaMask will soon stop reloading pages on network change.
   For more information, see: https://docs.metamask.io/guide/ethereum-provider.html#ethereum-autorefreshonnetworkchange 
   Set 'ethereum.autoRefreshOnNetworkChange' to 'false' to silence this warning.
   (anonymous) @ inpage.js:1
   Login.vue:372 Login failed Error: Invalid credentials
   at auth.js:36
   at tryCatch (pageHook.js:31744)
   at Generator.invoke [as _invoke] (pageHook.js:31970)
   at Generator.prototype.<computed> [as next] (pageHook.js:31796)
   at s (asyncToGenerator.js:5)
   at a (asyncToGenerator.js:27)
   DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/contentscript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
   DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/inpage.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
   DevTools failed to load SourceMap: Could not load content for chrome-extension://ibnejdfjmmkpcnlpebklmnkoeoihofec/dist/contentScript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
   DevTools failed to load SourceMap: Could not load content for chrome-extension://ibnejdfjmmkpcnlpebklmnkoeoihofec/dist/pageHook.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
   DevTools failed to load SourceMap: Could not load content for chrome-extension://flpiciilemghbmfalicajoolhkkenfel/static/js/contentScript.bundle.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME[/code]
   
  
    
   
  
   The errors with some js shown are the same as when I am able to use SteemConnect.
   
  
    
   
  
   So I can not get it to work with iOS Safari and Chrome now Windows Chrome.
   
    
   
    - Drew Dupont
    
   
     
    
     On Sep 7, 2020, at 10:28, Feruz M <notifications@github.com> wrote:
     
     
     
    
    
     
       
     I couldn't reproduce this issue, could you remove account and import account again only this time, uncheck Encrypt your keys box?

**Comment by feruzm** [comment] 2020-09-07 15:48
This error telling is that your private key is wrong. Can you share your username? Perhaps you changed your password/key on Hive or on Steem after the hardfork.

**Comment by TheNetWhiz** [comment] 2020-09-07 15:51
Ok, got it to work on Safari and Chrome with encrypt keys using Posting key. The page says Master or private key ... please change it to say Posting key instead.

Thank you,

- Drew Dupont

**Comment by feruzm** [comment] 2020-09-07 16:06
What key did you try that didn't work, Active private key?

**Comment by TheNetWhiz** [comment] 2020-09-07 16:09
Owner key. Posting key worked for Steem and Hive. But not when I went to delegate. Switched to Active and it worked to delegate.

Thank you,

- Drew Dupont

**Comment by feruzm** [comment] 2020-09-09 07:30
Ok, I will check why owner key is failing. I am working something relevant to improve prioritisation of keys during signing transaction, I think once that part is done, we shouldn't have any issues/confusions. I will keep this open for now until changes are pushed to production.

**Closed as completed** 2020-09-14 09:13 UTC
